# Generated by Django 5.0.3 on 2024-03-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('image', models.FileField(blank=True, upload_to='project_images/')),
                ('github', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
            ],
        ),
    ]
